### PR TITLE
Update with layout and title

### PR DESCRIPTION
**Pull request by dionew1**
Noticed that this page was broken as I was clicking around and checking out functionality.
@BrianZanti & @timomitchel I wanted to make sure you wanted this page to be live before making it part of gh-pages. Please merge if you want the page to be fixed.

### CODE REVIEW

**Review by timomitchel — COMMENTED** [review]
<Insert works on my machine comment> @dionew1 Thanks for adding this. I don't think we mind that it's live, but it's a work in progress.

**Comment by timomitchel** [comment]
I also kind of like that it's broken for you, because that's probably some kind of cache thing, and means it will likely be broken for students too. If you clear the cache does it work?

**Comment by dionew1** [comment]
@timomitchel I’m slightly confused by what you mean. 
On the M2 project index page when you click the link to navigate to this project it would not load because it was missing the title and layout section at the top of the page. Jekyll requires this section in order to serve up the page.

**Comment by timomitchel** [comment]
I see. Yea, I'm surprised, because I agree with you, but it works for me currently in the browser as is. Are you accessing it  locally or on the live site?

**Comment by timomitchel** [comment]
https://www.loom.com/share/406ad6f8b858452f8d17ec97ac30b430

**Comment by timomitchel** [comment]
Apologies for the sound. Feel free to mute.

**Comment by dionew1** [comment]
Oh interesting, I was testing things in development and didn’t double check production. Sorry for the trouble!

**Comment by timomitchel** [comment]
No trouble at all! @dionew1 -- I was interested to learn which environment it can and can't serve the page in. It's interesting that it will work in prod, because I didn't think it would be able to without that layout/title section, and when I was editing I forgot to add that back in. The more ya know!

**Pull request merged**
