### PR TITLE
add week 1 for review

### PR DESCRIPTION
**Pull request by icorson3**
WIP @s-espinosa please review

### CODE REVIEW

**Comment by s-espinosa** [comment]
@icorson3 This looks great! Let me know if you want me to merge or if you'd prefer to keep working on this branch for the other weeks. Thanks! 👍

**Comment by icorson3** [comment]
WIP @s-espinosa I will keep it open until I update the other weeks! Will mention you when I am ready to merge

**Comment by icorson3** [comment]
@s-espinosa ready to be looked over and merged

**Comment by icorson3** [comment]
I accidentally closed it

**Pull request merged**
