### PR TITLE
[WIP] Warmups

### PR DESCRIPTION
**Pull request by s-espinosa**
These need to be cleaned.

### CODE REVIEW

**Comment by s-espinosa** [comment]
@neight-allen @AliSchlereth 

Copied these from the app that Mike had created (maybe with Rachel?) to host morning exercises. Thought they should be stored in the curriculum repo. Will leave it up to you what to do with them from here.

**Comment by AliSchlereth** [comment]
Thanks @s-espinosa! 
Could you add another file that links to all the exercises you created for M1?

**Comment by s-espinosa** [comment]
@AliSchlereth Put those in the [Assessment Challenges repo](https://github.com/turingschool/assessment_challenges/blob/master/_backend/1module/diagnostics/independent_diagnostics.md), though it looks like the formatting could use some line breaks!

**Comment by AliSchlereth** [comment]
@s-espinosa Awesome, you're ahead of me.  Thanks! I'll merge this now.

**Pull request merged**
